name = "Create The Network"
author = "Otterlord"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3571e837772c194f893c6bf7eb47a46a7da4c2c99ff60c6d8c2243ed050b2152"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.99"
