name = "Create The Network"
author = "Otterlord"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd668c9a45ba5035739203d72806776212979d6758865603e3f80afcb1dfbab8"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.99"
